[package]
org = "ballerinax"
name = "nats"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[platform.java11.dependency]]
path = "./lib/jnats-@nats.client.version@.jar"
groupId = "io.nats"
artifactId = "jnats"
version = "@nats.client.version@"

[[platform.java11.dependency]]
path = "../nats-native/build/libs/nats-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "nats"
version = "@project.version@"
